name: Production build

on:
  release:
    types: [published]

env:
  RELEASE: resource-kit

jobs:
  build:
    timeout-minutes: 30
    name: Build - resource-kit
    runs-on: image-builder
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v3

      - name: Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/byzanteam/${{ env.RELEASE }}
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=ghcr.io/byzanteam/${{ env.RELEASE }}:buildcache
          cache-to: type=registry,ref=ghcr.io/byzanteam/${{ env.RELEASE }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            APP_VERSION=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}
            APP_REVISION=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.revision'] }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
